name: Update Site and Generate Sitemap

on:
  push:
    branches:
      - main # 或者 master，取决于您的主分支叫什么名字

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 新增步骤：获取当前日期并更新 index.html
      - name: Update last updated date
        run: |
          # 设置时区为纽约时间，并获取格式化的日期
          LAST_UPDATED_DATE=$(TZ="America/New_York" date +"%B %d, %Y")
          # 使用 sed 命令查找 id 为 "last-updated-date" 的 span 标签，并将日期填入
          sed -i 's|<span id="last-updated-date">.*</span>|<span id="last-updated-date">'"$LAST_UPDATED_DATE"'</span>|' index.html

      # 原有步骤：生成站点地图
      - name: Generate sitemap
        # !!! 改动在这里：将版本号从 @v1 更新为更具体的 @v1.9.0 !!!
        uses: cicirello/sitemap-generator-action@v1.9.0
        with:
          site_url: https://tl3049.github.io/

      # 修改步骤：提交 index.html 和 sitemap.xml 两个文件的更改
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-update site date and sitemap"
          # 将 index.html 添加到提交文件的列表中
          file_pattern: sitemap.xml index.html

