name: Update Site and Generate Sitemap

on:
  push:
    branches:
      - main # 或者 master，取决于您的主分支叫什么名字

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤1：获取当前日期并更新 index.html
      - name: Update last updated date
        run: |
          # 设置时区为纽约时间，并获取格式化的日期
          LAST_UPDATED_DATE=$(TZ="America/New_York" date +"%B %d, %Y")
          # 使用 sed 命令查找 id 为 "last-updated-date" 的 span 标签，并将日期填入
          sed -i 's|<span id="last-updated-date">.*</span>|<span id="last-updated-date">'"$LAST_UPDATED_DATE"'</span>|' index.html

      # 步骤2：用内置脚本生成站点地图
      - name: Generate sitemap with shell script
        run: |
          # 创建 sitemap.xml 文件并写入头部信息
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          
          # 查找仓库中所有的 .html 文件
          find . -name "*.html" | while read -r file; do
            # 排除谷歌验证文件
            if [[ "$file" == *google*.html ]]; then
              continue
            fi

            # 构建完整的URL地址
            LOC="https://tl3049.github.io/$(echo "$file" | sed 's|./||')"
            # 获取文件的最后修改日期
            LASTMOD=$(date -r "$file" +%Y-%m-%d)
            
            # 将页面的信息写入 sitemap.xml
            echo '  <url>' >> sitemap.xml
            echo "    <loc>$LOC</loc>" >> sitemap.xml
            echo "    <lastmod>$LASTMOD</lastmod>" >> sitemap.xml
            echo '  </url>' >> sitemap.xml
          done
          
          # 写入文件尾部信息
          echo '</urlset>' >> sitemap.xml
          echo "Sitemap generated successfully!"

      # 步骤3：提交 index.html 和 sitemap.xml 两个文件的更改
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # !!! 关键改动在这里：在提交信息中加入 [skip ci] 标签 !!!
          commit_message: "chore: Auto-update site date and sitemap [skip ci]"
          # 确保将 index.html 和 sitemap.xml 都包含在提交中
          file_pattern: sitemap.xml index.html

